export const ROADS = [
  { from: "HQ_DELHI", to: "CS_JAIPUR", route_name: "NH-48" },
  { from: "HQ_DELHI", to: "CS_JAIPUR", route_name: "SH-12" },
  { from: "HQ_DELHI", to: "CS_JAIPUR", route_name: "Link Road" },
  { from: "HQ_DELHI", to: "CS_LUCKNOW", route_name: "NH-48" },
  { from: "HQ_DELHI", to: "CS_LUCKNOW", route_name: "NH-30" },
  { from: "HQ_DELHI", to: "CS_LUCKNOW", route_name: "SH-25" },
  { from: "HQ_DELHI", to: "CS_CHANDIGARH", route_name: "NH-44" },
  { from: "HQ_DELHI", to: "CS_CHANDIGARH", route_name: "SH-7" },
  { from: "HQ_DELHI", to: "CS_CHANDIGARH", route_name: "Link Road" },
  { from: "HQ_MUMBAI", to: "CS_AHMEDABAD", route_name: "NH-48" },
  { from: "HQ_MUMBAI", to: "CS_AHMEDABAD", route_name: "NH-8 Express" },
  { from: "HQ_MUMBAI", to: "CS_AHMEDABAD", route_name: "SH-50" },
  { from: "HQ_MUMBAI", to: "CS_INDORE", route_name: "NH-52" },
  { from: "HQ_MUMBAI", to: "CS_INDORE", route_name: "SH-31" },
  { from: "HQ_MUMBAI", to: "CS_INDORE", route_name: "Link Route" },
  { from: "HQ_MUMBAI", to: "CS_PUNE", route_name: "Expressway" },
  { from: "HQ_MUMBAI", to: "CS_PUNE", route_name: "NH-48" },
  { from: "HQ_MUMBAI", to: "CS_PUNE", route_name: "Old Pass" },
  { from: "HQ_MUMBAI", to: "CS_NAGPUR", route_name: "NH-44" },
  { from: "HQ_MUMBAI", to: "CS_NAGPUR", route_name: "SH-266" },
  { from: "HQ_MUMBAI", to: "CS_NAGPUR", route_name: "Via Aurangabad" },
  { from: "HQ_MUMBAI", to: "CS_BHOPAL", route_name: "NH-46" },
  { from: "HQ_MUMBAI", to: "CS_BHOPAL", route_name: "SH-18" },
  { from: "HQ_MUMBAI", to: "CS_BHOPAL", route_name: "Link Corridor" },
  { from: "HQ_BANGALORE", to: "CS_CHENNAI", route_name: "NH-48" },
  { from: "HQ_BANGALORE", to: "CS_CHENNAI", route_name: "SH-4" },
  { from: "HQ_BANGALORE", to: "CS_CHENNAI", route_name: "Express Route" },
  { from: "HQ_BANGALORE", to: "CS_HYDERABAD", route_name: "NH-44" },
  { from: "HQ_BANGALORE", to: "CS_HYDERABAD", route_name: "SH-20" },
  { from: "HQ_BANGALORE", to: "CS_HYDERABAD", route_name: "Link Road" },
  { from: "HQ_BANGALORE", to: "CS_KOCHI", route_name: "NH-66" },
  { from: "HQ_BANGALORE", to: "CS_KOCHI", route_name: "SH-17" },
  { from: "HQ_BANGALORE", to: "CS_KOCHI", route_name: "Coastal Route" },
  { from: "HQ_KOLKATA", to: "CS_PATNA", route_name: "NH-19" },
  { from: "HQ_KOLKATA", to: "CS_PATNA", route_name: "SH-78" },
  { from: "HQ_KOLKATA", to: "CS_PATNA", route_name: "Alternate NH" },
  { from: "HQ_KOLKATA", to: "CS_RANCHI", route_name: "NH-33" },
  { from: "HQ_KOLKATA", to: "CS_RANCHI", route_name: "SH-5" },
  { from: "HQ_KOLKATA", to: "CS_RANCHI", route_name: "Link Road" },
  { from: "HQ_KOLKATA", to: "CS_BHUBANESHWAR", route_name: "NH-16" },
  { from: "HQ_KOLKATA", to: "CS_BHUBANESHWAR", route_name: "SH-60" },
  { from: "HQ_KOLKATA", to: "CS_BHUBANESHWAR", route_name: "Coastal Road" },
  { from: "HQ_KOLKATA", to: "CS_GUWAHATI", route_name: "NH-27" },
  { from: "HQ_KOLKATA", to: "CS_GUWAHATI", route_name: "NH-17" },
  { from: "HQ_KOLKATA", to: "CS_GUWAHATI", route_name: "Siliguri Pass" },
]